# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Program\Eric6\HITers\grade_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(828, 513)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/HITers.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        self.buttonQuery = QtWidgets.QPushButton(Dialog)
        self.buttonQuery.setGeometry(QtCore.QRect(660, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.buttonQuery.setFont(font)
        self.buttonQuery.setObjectName("buttonQuery")
        self.buttonCalcu = QtWidgets.QPushButton(Dialog)
        self.buttonCalcu.setGeometry(QtCore.QRect(660, 440, 91, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.buttonCalcu.setFont(font)
        self.buttonCalcu.setObjectName("buttonCalcu")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 21, 791, 321))
        self.tableWidget.setStyleSheet("QHeaderView::section{background:rgb(85, 170, 255)};")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.radioNow = QtWidgets.QRadioButton(Dialog)
        self.radioNow.setGeometry(QtCore.QRect(320, 410, 89, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.radioNow.setFont(font)
        self.radioNow.setObjectName("radioNow")
        self.radioPast = QtWidgets.QRadioButton(Dialog)
        self.radioPast.setGeometry(QtCore.QRect(320, 450, 101, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.radioPast.setFont(font)
        self.radioPast.setChecked(True)
        self.radioPast.setObjectName("radioPast")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 390, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 450, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineStuid = QtWidgets.QLineEdit(Dialog)
        self.lineStuid.setGeometry(QtCore.QRect(90, 380, 161, 31))
        self.lineStuid.setObjectName("lineStuid")
        self.linePwd = QtWidgets.QLineEdit(Dialog)
        self.linePwd.setGeometry(QtCore.QRect(90, 440, 161, 31))
        self.linePwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.linePwd.setObjectName("linePwd")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "成绩管理"))
        self.buttonQuery.setText(_translate("Dialog", "成绩查询"))
        self.buttonCalcu.setText(_translate("Dialog", "绩点计算"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "课程名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "学分"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "实验成绩"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "平时成绩"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "期末成绩"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "总成绩"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "考试类型"))
        self.radioNow.setText(_translate("Dialog", "本学期成绩"))
        self.radioPast.setText(_translate("Dialog", "以往所有成绩"))
        self.label.setText(_translate("Dialog", "学号"))
        self.label_2.setText(_translate("Dialog", "密码"))

from res import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

